version: "3"
services: 
  backend:
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    command: bash -c "npm install && npm run start:watch"
  db:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_MY_DATABASE: ${DB_NAME}
    env_file: .env
    volumes: 
      - pgrdata:/data
    ports: 
      - ${DB_PORT}:${DB_PORT}
volumes:
    pgrdata:
      external: true